version: "3.8"

services:

  mongodb:
    image: mongo:7
    container_name: flower-mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  flower-app:
    build: .
    container_name: flower-app-new
    restart: always
    ports:
      - "3015:3015"
    env_file:
      - .env
    depends_on:
      - mongodb

volumes:
  mongo-data:
